-- MySQL Script generated by MySQL Workbench
-- Fri Jun 20 20:35:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tarefas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tarefas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tarefas` DEFAULT CHARACTER SET utf8 ;
USE `tarefas` ;

-- -----------------------------------------------------
-- Table `tarefas`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarefas`.`table1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeTarefa` VARCHAR(45) NOT NULL,
  `descricaoTarefa` VARCHAR(255) NULL,
  `statusTarefa` ENUM("Concluido", "Em Andamento") NULL,
  `dataTarefa` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tempoParaFazerTarefa` VARCHAR(45) NULL,
  `opniãoTarefaRealizada` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- DROP DATABASE tarefas;

-- INSERT INTO `tarefas`.`table1` (id, nomeTarefa, descricaoTarefa, statusTarefa, dataTarefa, tempoParaFazerTarefa, opniãoTarefaRealizada) VALUES (1,'TAREFATESTE');
